parameters:
  - name: TargetBranch
    type: string
    default: ''

steps:
  - checkout: self
    clean: true
    fetchDepth: 1
    persistCredentials: true

  - task: PowerShell@2
    displayName: "Configure user"
    inputs:
      targetType: "inline"
      script: |
        git config --global user.email "peter.ombwa@outlook.com"
        git config --global user.name "Peter"

  - task: Bash@3
    displayName: "Switch branch to target branch: $(TargetBranch)"
    condition: and(succeeded(), ne('${{ parameters.TargetBranch }}', ''))
    inputs:
      targetType: inline
      script: |
        echo "Target branch:"
        echo $(TargetBranch)
        git status
        git fetch --all
        git checkout $(TargetBranch)
        git pull
        git status