# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  Branch: WeeklyOpenApiDocsDownload
  BaseBranch: main

trigger: none
pr: none
schedules:
  - cron: "50 21 * * TUE"
    displayName: "Weekly PS SDK generation"
    branches:
      include:
        - main
    always: true

stages:
# Proposed Weekly OpenAPI docs Steps:
# - Create WeeklyOpenAPIRefresh\{{Date}} from 'main' and checkout.
# - Download OpenAPI documents and commit.
# - Build entire SDK & run tests.
# - Create CommandModuleMapping and commit.
# - Push changes to WeeklyOpenAPIRefresh\{{Date}} branch with [run CI] commit message.
## GH action.
# - On commit with `[run CI]` tag, create PR to latest `releases\(version)` where version = (current PS Gallery + 0.0.1 when latest local version = PS Gallery); otherwise, use latest local version.

## Online REF docs:
# - Create new 'DocsUpdate/{{Date}}' branch from 'main'.
# - Generate docs and commit.
  - stage: DownloadOpenAPIDocs
    displayName: Download OpenAPI docs
    jobs:
      - template: common-templates/download-openapi-docs.yml
        parameters:
          Branch: $(Branch)
          BaseBranch: $(BaseBranch)

  # - stage: GenerateServiceModules
  #   displayName: Generate service modules
  #   jobs:
  #     - template: generation-templates/generate-service-modules.yml
  #       parameters:
  #         Branch: $[ stageDependencies.DownloadOpenAPIDocs.GetLatestDocs.outputs['ComputeBranch.WeeklyBranch'] ]
  #         AuthModulePath: "src/Authentication/Authentication"
  #         ServiceModulePath: "src/"
  #         ModulePrefix: "Microsoft.Graph"
  #         EnableSigning: false
  #         PublishToFeed: false
  #         GenerateCommandMetadata: true
  #         GenerateHelpDocs: true
